### ISSUE TITLE
Doesn't start, unable to init server

### ISSUE THREAD

**Issue by kabo** [Androxyde/Flashtool#106]
Downloaded and extracted the torrent from http://www.flashtool.net/downloads_linux.php

```
$ sudo ./FlashTool
Running as root.
Used java home : ./x10flasher_lib/linjre64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/user/Downloads/FlashTool/x10flasher_lib/groovy-3.0.0-alpha-2-indy.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
01/035/2019 21:35:46 - INFO  - <- This level is successfully initialized
No protocol specified
Unable to init server: Could not connect: Connection refused
Exception in thread "main" org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
        at org.eclipse.swt.SWT.error(SWT.java:4578)
        at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1007)
        at org.eclipse.swt.widgets.Display.create(Display.java:994)
        at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:577)
        at org.eclipse.swt.widgets.Display.<init>(Display.java:568)
        at org.eclipse.swt.widgets.Display.getDefault(Display.java:2445)
        at gui.MainSWT.open(MainSWT.java:118)
        at gui.Main.main(Main.java:46)
```

Running Debian Buster.

**Comment by kabo** [comment]
And it's running Wayland, could that be it?

**Comment by kabo** [comment]
Running `xhost local:root` as mentioned in https://github.com/Androxyde/Flashtool/blob/master/TROUBLESHOOTING.md fixed it.
