### ISSUE TITLE
error when trying to initialize BLU on xz2c

### ISSUE THREAD

**Issue by lieuxnoir** [Androxyde/Flashtool#162]
Device: Xperia XZ2 Compact (SO-05K, bootloader unlocked)
OS: Arch Linux
Flashtool version used: 0.9.33.0

Description: I am trying to relock the bootloader on my device. Upon plugging, flashtool detected the device but then it ends in an error as shown in the logs.

Log from the program:
```
18/003/2021 01:03:10 - INFO  - <- This level is successfully initialized
18/003/2021 01:03:11 - INFO  - JAVA_HOME : /home/lieu/Downloads/flashtool-0.9.33.0-linux/FlashTool/x10flasher_native/jre
18/003/2021 01:03:11 - INFO  - Flashtool 0.9.33.0
18/003/2021 01:03:11 - INFO  - libusb version 1.0.23
18/003/2021 01:03:11 - INFO  - Searching for a web proxy
18/003/2021 01:03:11 - INFO  - A proxy has been found. Using it as default
18/003/2021 01:03:11 - INFO  - Syncing devices from github
18/003/2021 01:03:12 - INFO  - Opening devices repository.
18/003/2021 01:03:12 - INFO  - Scanning devices folder for changes.
18/003/2021 01:03:18 - INFO  - Pulling changes from github.
18/003/2021 01:03:20 - INFO  - Devices sync finished.
18/003/2021 01:03:20 - INFO  - Loading devices database
18/003/2021 01:03:20 - INFO  - Loaded 131 devices
18/003/2021 01:03:20 - INFO  - Starting phone detection
18/003/2021 01:03:21 - INFO  - Device disconnected
18/003/2021 01:03:24 - DEBUG - (null:-1) - <- This level is successfully initialized
18/003/2021 01:03:32 - INFO  - (null:-1) - Please connect your device into flashmode.
18/003/2021 01:03:48 - INFO  - (null:-1) - Opening device for R/W
18/003/2021 01:03:48 - INFO  - (null:-1) - Device ready for R/W.
18/003/2021 01:03:48 - INFO  - (null:-1) - Reading device information
18/003/2021 01:03:48 - INFO  - (null:-1) - Reading phone properties
18/003/2021 01:03:48 - INFO  - (null:-1) - Sending getvar:product
18/003/2021 01:03:48 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:48 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@53097857
18/003/2021 01:03:48 - INFO  - (null:-1) -    getvar status : OKAY
18/003/2021 01:03:48 - INFO  - (null:-1) - Sending Read-TA:2:2202
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@e9d6c3
18/003/2021 01:03:49 - INFO  - (null:-1) -    Read-TA status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Sending Read-TA:2:2205
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@68ae1d22
18/003/2021 01:03:49 - INFO  - (null:-1) -    Read-TA status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Sending Read-TA:2:2210
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@530c3257
18/003/2021 01:03:49 - INFO  - (null:-1) -    Read-TA status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Sending Read-TA:2:4900
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@3da5c6e7
18/003/2021 01:03:49 - INFO  - (null:-1) -    Read-TA status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Sending Read-TA:2:10021
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@32b8d16c
18/003/2021 01:03:49 - INFO  - (null:-1) -    Read-TA status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Sending Get-root-key-hash
18/003/2021 01:03:49 - DEBUG - (null:-1) - Reading packet from phone
18/003/2021 01:03:49 - DEBUG - (null:-1) - IN : flashsystem.CommandPacket@60ec9e45
18/003/2021 01:03:49 - INFO  - (null:-1) -    Get-root-key-hash status : OKAY
18/003/2021 01:03:49 - INFO  - (null:-1) - Connected device : SO-05K / SW release 1311-9109_52.1.B.0.266 / Customization 1315-7886_R9C
18/003/2021 01:03:49 - INFO  - (null:-1) - Last flash date : 2021-01-17 23:34:04
18/003/2021 01:03:49 - INFO  - (null:-1) - Phone ready for flashmode operations.
18/003/2021 01:03:49 - ERROR - (null:-1) - Cannot invoke "String.split(String)" because the return value of "java.util.Properties.getProperty(String)" is null
```

Log from the terminal:
```
18/003/2021 01:03:10 - INFO  - <- This level is successfully initialized
18/003/2021 01:03:11 - INFO  - JAVA_HOME : /home/lieu/Downloads/flashtool-0.9.33.0-linux/FlashTool/x10flasher_native/jre
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.util.Properties.getProperty(String)" is null
        at flashsystem.CommandFlasher.getIMEI(Unknown Source)
        at gui.tools.GetULCodeJob.run(Unknown Source)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by frago21ps** [comment]
Same here for xz2
