### ISSUE TITLE
Loader.Sin Issue

### ISSUE THREAD

**Issue by Harleythetech** [Androxyde/Flashtool#172]
I Have Issues where When i Want to Flash Nougat 7.1.1 to my Xperia Z5 (dual) Flash Tools always Ends up with an Error of 

22/039/2021 11:39:00 - ERROR - (X10flash.java:326) - Processing of loader.sin finished with errors.
22/002/2021 12:02:09 - ERROR - (X10flash.java:727) - Error in processHeader : 1 : Incorrect function. 
22/002/2021 12:02:09 - ERROR - (X10flash.java:728) - Error flashing. Aborted

As of right now im trying it again but i bet this will show the same issue. the FTF file i have is an official OS i removed the loader.sin to try flashing it directly but no luck at all it still requires me to have the loader to be there.

![image](https://user-images.githubusercontent.com/51787264/126588472-51a6b849-6c1d-4654-8f16-c55b5caafd1f.png)

Both loader.sin that come from OS and Flashtool doesn't work :(

**Comment by SSDMT-DEV-HARLEY** [comment]
Stderr.log

`java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at gui.models.TreeDevices.<init>(TreeDevices.java:24)
	at gui.FTFSelector.updateContent(FTFSelector.java:326)
	at gui.FTFSelector.open(FTFSelector.java:105)
	at gui.MainSWT.doFlashmode(MainSWT.java:1393)
	at gui.MainSWT.doFlash(MainSWT.java:1374)
	at gui.MainSWT$39.widgetSelected(MainSWT.java:1019)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4415)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4233)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3821)
	at gui.MainSWT.open(MainSWT.java:176)
	at gui.Main.main(Main.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at gui.models.TreeDevices.<init>(TreeDevices.java:24)
	at gui.FTFSelector.updateContent(FTFSelector.java:326)
	at gui.FTFSelector.open(FTFSelector.java:105)
	at gui.MainSWT.doFlashmode(MainSWT.java:1393)
	at gui.MainSWT.doFlash(MainSWT.java:1374)
	at gui.MainSWT$39.widgetSelected(MainSWT.java:1019)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4415)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4233)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3821)
	at gui.MainSWT.open(MainSWT.java:176)
	at gui.Main.main(Main.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at gui.models.TreeDevices.<init>(TreeDevices.java:24)
	at gui.FTFSelector.updateContent(FTFSelector.java:326)
	at gui.FTFSelector.open(FTFSelector.java:105)
	at gui.MainSWT.doFlashmode(MainSWT.java:1393)
	at gui.MainSWT.doFlash(MainSWT.java:1374)
	at gui.MainSWT$39.widgetSelected(MainSWT.java:1019)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4415)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4233)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3821)
	at gui.MainSWT.open(MainSWT.java:176)
	at gui.Main.main(Main.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
java.io.IOException: Read error :1 : Incorrect function. 
	at win32lib.JKernel32.readBytes(JKernel32.java:59)
	at flashsystem.io.USBFlashWin32.windowsReadS1Reply(USBFlashWin32.java:81)
	at flashsystem.io.USBFlash.readS1Reply(USBFlash.java:59)
	at flashsystem.X10flash.openDevice(X10flash.java:956)
	at flashsystem.X10flash.openDevice(X10flash.java:886)
	at gui.tools.FlashJob.run(FlashJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
java.io.IOException: 1 : Incorrect function. 
	at flashsystem.Command.writeCommand(Command.java:120)
	at flashsystem.Command.send(Command.java:127)
	at flashsystem.X10flash.openTA(X10flash.java:426)
	at flashsystem.X10flash.getDevInfo(X10flash.java:562)
	at flashsystem.X10flash.openDevice(X10flash.java:972)
	at flashsystem.X10flash.openDevice(X10flash.java:886)
	at gui.tools.FlashJob.run(FlashJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
flashsystem.X10FlashException: Error in processHeader : 1 : Incorrect function. 
	at flashsystem.X10flash.processHeader(X10flash.java:296)
	at flashsystem.X10flash.uploadImage(X10flash.java:307)
	at flashsystem.X10flash.sendLoader(X10flash.java:372)
	at flashsystem.X10flash.flashDevice(X10flash.java:708)
	at gui.tools.FlashJob.run(FlashJob.java:44)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
flashsystem.X10FlashException: Error in processHeader : 1 : Incorrect function. 
	at flashsystem.X10flash.uploadImage(X10flash.java:329)
	at flashsystem.X10flash.sendLoader(X10flash.java:372)
	at flashsystem.X10flash.flashDevice(X10flash.java:708)
	at gui.tools.FlashJob.run(FlashJob.java:44)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`
	
stdout.log

`22/058/2021 11:58:41 - DEBUG - (MyLogger.java:82) - <- This level is successfully initialized
`
