### ISSUE TITLE
Can't flash Android 12 to Xperia 5 II

### ISSUE THREAD

**Issue by Peca21** [Androxyde/Flashtool#176]
Flash gets stuck somewhere on the beginning
Log here: https://pastebin.com/KBYntHSb

**Comment by Peca21** [comment]
Managed to flash it:
1. Download xperifirm (doesn't work in flashtool)
2. Download firmware (mine was 58.2.A.0.899 Customized EEA)
3. Open flashtool -> Tools -> Bundles -> Create
4. Select all on the left and move to the right
5. Device XQ-AS52 / Branding Customized EEA / Version 58.2.A.0.899 -> Create
6. Find the ftf file and open it with something like winrar
7. Extract boot_delivery.xml from the ftf
8. delete boot_delivery.xml in the ftf
9. open boot folder in ftf
10. place  boot_delivery.xml into boot folder in ftf
11. Go to C:\Users\Zajo\.flashTool\devices\XQ-AS
12. Rename 58.0.fsc to 58.2.fsc (First numbers in version)
13. Select flashmode -> select ftf -> flash
14. Power off your phone
15. Hold volume down and at the same time plugin in USB
16. Done

**Comment by KOPRajs** [comment]
And how about partition_delivery.xml?

**Comment by KOPRajs** [comment]
When using the unmodified FTF the log says:
- INFO  - Parsing boot delivery
- ERROR - null

While the log after moving the boot_delivery.xml into the boot/ says:
- INFO  - No boot delivery into the bundle

So it seems that moving the boot_delivery.xml into the boot/ folder of the FTF is the same as to remove it completely.

**Comment by invincible30** [comment]
> Managed to flash it:
> 
> 1. Download xperifirm (doesn't work in flashtool)
> 2. Download firmware (mine was 58.2.A.0.899 Customized EEA)
> 3. Open flashtool -> Tools -> Bundles -> Create
> 4. Select all on the left and move to the right
> 5. Device XQ-AS52 / Branding Customized EEA / Version 58.2.A.0.899 -> Create
> 6. Find the ftf file and open it with something like winrar
> 7. Extract boot_delivery.xml from the ftf
> 8. delete boot_delivery.xml in the ftf
> 9. open boot folder in ftf
> 10. place  boot_delivery.xml into boot folder in ftf
> 11. Go to C:\Users\Zajo.flashTool\devices\XQ-AS
> 12. Rename 58.0.fsc to 58.2.fsc (First numbers in version)
> 13. Select flashmode -> select ftf -> flash
> 14. Power off your phone
> 15. Hold volume down and at the same time plugin in USB
> 16. Done

Thanks a lot lot lot... muah..... you saved my day and my phone. Thanks again.

**Comment by frapta** [comment]
Hi,

since the flashtool does not seem to work properly when pressing Xperifirm button:

_java.lang.NullPointerException: Cannot invoke "org.system.ProcessBuilderWrapper.getStdOut()" because "<local4>" is null
	at org.util.XperiFirm.run(Unknown Source)
	at gui.tools.XperiFirmJob.run(Unknown Source)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)_

I tried what Peca21 suggested above, but my Xperifirm (standalone) does not work either, always comes up with 'can't connect to server'error regardless of its version, my LAN settings, antivirus etc ...

Any suggestion please on how to get it working?

**Comment by Peca21** [comment]
> I tried what Peca21 suggested above, but my Xperifirm (standalone) does not work either, always comes up with 'can't connect to server'error regardless of its version, my LAN settings, antivirus etc ...
>Any suggestion please on how to get it working?
Which version of xperifirm are you using? I have 5.6.5

**Comment by frapta** [comment]
Thanks! Yes I was on 5.4.0 downoloaded from xperifirm.com, now thanks to your hint I use 5.6.5 from xperifirmtool.com and that one works ;-) Did not know there are two sites online!

However somewhere along the path to get it somehow working my flashtool now does not work :-(
Starting with long error: "ERROR - Cannot access file with path exceeding 32000 characters
java.io.IOException: Cannot access file with path exceeding 32000 characters ..." and at the end "ERROR - No device is registered in Flashtool". So I have the firmware required in the Lineage installation guide, but can't move forward anyway... Any ideas for desperate man?

Flashtool with its drivers - removed and installed again without errors, device manager status OK, ADB sees the device ... Running on Win 10, using Flashtool 0.9.34.0

**Comment by frapta** [comment]
so I have got a step further on a different PC, managed to download the firmware using standalone Xperifirm, mine is "D5803_Customized CE1_23.5.A.1.291-R2D", pointed Flashtool to it, moved all the found files to the right, but I can't enter anything into the "device" field :-(
Branding and Version are editable, but the Device is greyed out and it won't let me type. Tried it on 9.34 and even on 9.33 version of Flashtool, both to no avail.

What am I doing wrong this time?

**Comment by Peca21** [comment]
> so I have got a step further on a different PC, managed to download the firmware using standalone Xperifirm, mine is "D5803_Customized CE1_23.5.A.1.291-R2D", pointed Flashtool to it, moved all the found files to the right, but I can't enter anything into the "device" field :-( Branding and Version are editable, but the Device is greyed out and it won't let me type. Tried it on 9.34 and even on 9.33 version of Flashtool, both to no avail.
> 
> What am I doing wrong this time?

you should be able to double click it which should show a window of all devices

![image](https://user-images.githubusercontent.com/13818400/169414196-8110f538-9685-4ace-9dd6-946742c5b33f.png)

**Comment by frapta** [comment]
wow, stupid mistake :-( yes that works. Thank you so much.

But it seems my destiny is not to have my phone flashed. Once the bundle was created and flashed to phone succesfully, the first boot after the flash (ticked only all the wipe boxes) ended up with NFC firmware flash failed (-1) :-( So I'm back to where I started. 

Btw. does this flashing procedure changes 'Bootloader unlock allowed' to 'Yes'?
Mine at the moment says 'NO', hence I can't continue with the install anyway, right?

**Comment by Peca21** [comment]
It doesn't have to be unlocked. You can also try newflasher I think it's called. Also watch out for bad cables mine lost connection during flashing with no errors visible, had to get a new cable.
