### ISSUE TITLE
Flashtool won't startup, Java Error

### ISSUE THREAD

**Issue by nyanggo** [Androxyde/Flashtool#18]
Flashtool 0.9.18.6,
it won't startup, and stderr.log is made everytime i try to open.
 - Windows 8.1 64bit

this is the contents of stderr.log.
------------------------------------------------------------------------------------------------------------------------
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.btr.proxy.search.browser.firefox.FirefoxProxySearchStrategy.getProxySelector(FirefoxProxySearchStrategy.java:96)
	at com.btr.proxy.search.ProxySearch.getProxySelector(ProxySearch.java:192)
	at org.system.Proxy.setProxy(Proxy.java:30)
	at gui.MainSWT.createContents(MainSWT.java:1019)
	at gui.MainSWT.open(MainSWT.java:116)
	at gui.Main.main(Main.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
------------------------------------------------------------------------------------------------------------------------

**Comment by Androxyde** [comment]
Disable your Firefox proxy settings
