### ISSUE TITLE
i am getting java error

### ISSUE THREAD

**Issue by manojcool** [Androxyde/Flashtool#19]

**Comment by Androxyde** [comment]
What kind ?

**Comment by manojcool** [comment]
java.lang.ClassNotFoundException: gui.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)

**Comment by manojcool** [comment]
windows 7
