### ISSUE TITLE
org.flashtool.libusb.LibUsbException: Libusb not found  although it is already installed on macOS

### ISSUE THREAD

**Issue by sebma** [Androxyde/Flashtool#207]
Hi,
I have this error on macOS 12.6 : 
```bash
$ /Applications/FlashTool.app/Contents/MacOS/FlashTool
/Applications/FlashTool.app/Contents/MacOS/x10flasher_native/udev
22/17/2023 18:17:00 - INFO  - <- This level is successfully initialized
22/17/2023 18:17:00 - INFO  - JAVA_HOME : /Applications/FlashTool.app/Contents/MacOS/jre
org.flashtool.libusb.LibUsbException: Libusb not found. Minimum libusb version is 1.0.15. It can be downloaded on http://www.libusbx.org
	at org.flashtool.libusb.UsbSystem.initSystem(UsbSystem.java:32)
	at org.flashtool.libusb.UsbSystem.<init>(UsbSystem.java:19)
	at org.flashtool.jna.linux.JUsb.init(JUsb.java:24)
	at org.flashtool.gui.Main.initLinuxUsb(Main.java:83)
	at org.flashtool.gui.Main.run(Main.java:65)
	at org.flashtool.gui.Main.main(Main.java:49)
```
but libusb v1.0.26 is already installed : 
```bash
$ brew info libusb
==> libusb: stable 1.0.26 (bottled), HEAD
Library for USB device access
https://libusb.info/
/usr/local/Cellar/libusb/1.0.26 (22 files, 531.7KB) *
  Poured from bottle on 2022-12-30 at 00:57:31
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libusb.rb
License: LGPL-2.1-or-later
==> Options
--HEAD
	Install HEAD version
$
```

**Comment by nms42** [comment]
In folder `FlashTool.app/Contents/MacOS/x10flasher_native/udev` there is incorrect symlink

`libusbx-1.0.dylib -> /Users/emmanuel/git/Flashtool/Flashtool/build/install/Flashtool/FlashTool.app/Contents/MacOS/x10flasher_native/udev/libusbx-1.0.0.dylib`

Should it be `libusbx-1.0.dylib -> libusbx-1.0.0.dylib`?

**Comment by MartinVonReichenberg** [comment]
> In folder `FlashTool.app/Contents/MacOS/x10flasher_native/udev` there is incorrect symlink
> 
> `libusbx-1.0.dylib -> /Users/emmanuel/git/Flashtool/Flashtool/build/install/Flashtool/FlashTool.app/Contents/MacOS/x10flasher_native/udev/libusbx-1.0.0.dylib`
> 
> Should it be `libusbx-1.0.dylib -> libusbx-1.0.0.dylib`?


If it is meant to be a UNIX/POSIX-like symlink then you can use any name you want/need for the link pointing to the source . . .

**Comment by biaji** [comment]
> In folder `FlashTool.app/Contents/MacOS/x10flasher_native/udev` there is incorrect symlink
> 
> `libusbx-1.0.dylib -> /Users/emmanuel/git/Flashtool/Flashtool/build/install/Flashtool/FlashTool.app/Contents/MacOS/x10flasher_native/udev/libusbx-1.0.0.dylib`
> 
> Should it be `libusbx-1.0.dylib -> libusbx-1.0.0.dylib`?

`ln -sf libusbx-1.0.0.dylib libusbx-1.0.dylib`

and it's work like a charm

the origin code caused this is :

```java
  public static final LibUsbLibrary libUsb = (LibUsbLibrary)Native.loadLibrary("usbx-1.0", LibUsbLibrary.class);
```
