### ISSUE TITLE
Error in processHeader while try ti flash "xperia mini pro sk17i" with flashtool-0.9.19.10

### ISSUE THREAD

**Issue by Fedik** [Androxyde/Flashtool#31]
While I tried to flash my sk17i I always get error `Processing of loader.sin finished with errors.`
I use Ubuntu 14.04, I also tried on Windows, but error exactly the same.

Trace:
```
$ ./FlashTool
Not running as root but Sony/SonyEriccson Vendor ID found on your udev rules
if Flashing didn't work well, run flashtool as root
Used java home : ./x10flasher_lib/linjre64
flashsystem.X10FlashException: Error in processHeader : null
	at flashsystem.X10flash.processHeader(X10flash.java:313)
	at flashsystem.X10flash.uploadImage(X10flash.java:324)
	at flashsystem.X10flash.sendLoader(X10flash.java:404)
	at flashsystem.X10flash.flashDevice(X10flash.java:759)
	at gui.tools.FlashJob.run(FlashJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
flashsystem.X10FlashException: Error in processHeader : null
	at flashsystem.X10flash.uploadImage(X10flash.java:344)
	at flashsystem.X10flash.sendLoader(X10flash.java:404)
	at flashsystem.X10flash.flashDevice(X10flash.java:759)
	at gui.tools.FlashJob.run(FlashJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Full log with Debug enabled: https://drive.google.com/open?id=0B7Ad4gohdViicUdhcC1aQ2ZSMUE

However older version flashtool-0.9.10.1-linux works good.

**Comment by nix-31** [comment]
I have a similar issue trying to flash stock ROM on Xperia Mini sk17a using Flashtool 0.9.22.3 on Windows 10 x64. Error log:
```

20/007/2016` 04:07:38 - INFO  - Device connected in flash mode
20/008/2016 04:08:11 - INFO  - Selected Bundle for SonyEricson Xperia Mini Pro(SK17i). FW release : 4.0.2.A.0.62. Customization : (1251-0103)
20/008/2016 04:08:11 - INFO  - Preparing files for flashing
20/008/2016 04:08:15 - INFO  - Please connect your device into flashmode.
20/008/2016 04:08:15 - INFO  - Opening device for R/W
20/008/2016 04:08:15 - INFO  - Reading device information
20/008/2016 04:08:18 - INFO  - Unable to read from phone after having opened it.
20/008/2016 04:08:18 - INFO  - trying to continue anyway
20/008/2016 04:08:18 - INFO  - Phone ready for flashmode operations.
20/008/2016 04:08:18 - INFO  - Opening TA partition 2
20/008/2016 04:08:18 - INFO  - Start Flashing
20/008/2016 04:08:18 - INFO  - Processing loader.sin
20/008/2016 04:08:18 - INFO  -     Checking header
20/008/2016 04:08:18 - ERROR - Processing of loader.sin finished with errors.
20/008/2016 04:08:18 - INFO  - Ending flash session
20/008/2016 04:08:18 - ERROR - Error in processHeader : 22 : The device does not recognize the command. 
20/008/2016 04:08:18 - ERROR - Error flashing. Aborted
20/008/2016 04:08:18 - INFO  - Device disconnected
```

I would like to request a download link to flashtool 0.9.10.1 (preferably Windows) to try and solve my problem in the meantime. Do you have it, @Fedik ?

**Comment by Fedik** [comment]
sorry, I think I have already removed it
