### ISSUE TITLE
Can't open flashtool

### ISSUE THREAD

**Issue by thecryptzen** [Androxyde/Flashtool#33]
Help i can't open flashtool and it shows a stderr file.

java.lang.NullPointerException
	at org.logger.MyLogger.initProperties(MyLogger.java:36)
	at org.logger.MyLogger.setLogDest(MyLogger.java:28)
	at gui.Main.main(Main.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)

My laptop is running on Windows XP 32-bit
Please help me because my device is having a bootloop and i can't any other way to fix it!

**Comment by r2stik** [comment]
Xperia Z5, Z5c, Z5P DRIVERS ERROR ON FLASHTOOL!

**Comment by P-Axe** [comment]
Deleting the folder c:\users\your_username\.flashtool
will make it run again, at least on Windows 7 x64.

**Comment by inteman2** [comment]
Deleting the folder worked for me as well
using windows 10 x64 here

**Comment by coolexeqiang** [comment]
thanks~ its work for me

**Comment by mouradsme** [comment]
it worked for me as well!
Thank you very much! :+1:
