### ISSUE TITLE
Java-Files not found (Linux)

### ISSUE THREAD

**Issue by Schweineschwarte** [Androxyde/Flashtool#36]
My system: openSUSE 42.1 64bit with KDE

If I want to start FlashTool as root, it calls:
linux-f9t1:/home/schweineschwarte/Downloads/Xperia J/Flashtool-master/ProgramExe # sh FlashTool
Running as root.
Used java home : ./x10flasher_lib/linjre64
ls: Zugriff auf ./x10flasher_lib/*jar nicht möglich: Datei oder Verzeichnis nicht gefunden
ldd: x10flasher_lib/linux/lib32/udev/libusbx-1.0.so.0.1.0: Datei oder Verzeichnis nicht gefunden
ls: Zugriff auf ./x10flasher_lib/swtlin/x86/*jar nicht möglich: Datei oder Verzeichnis nicht gefunden
FlashTool: Zeile 74: ./x10flasher_lib/linjre64/bin/java: Datei oder Verzeichnis nicht gefunden

I have download the zip-file from github and extract it full.

**Comment by bungabunga** [comment]
same here on Ubuntu 16.04. i guess it has something to do with java upgrade since the same Flashtool installe version did work on the same computer many times before.

`Running as root.
Used java home : ./x10flasher_lib/linjre64
Exception in thread "main" java.lang.NullPointerException
	at org.logger.MyLogger.setLevel(MyLogger.java:59)
	at gui.Main.main(Main.java:29)`

**Comment by Androxyde** [comment]
You cannot run Flashtool from github sources. You have to build and deploy the solution before being able to run it.

**Comment by Schweineschwarte** [comment]
I don't find any instruction how to do this. How is it possible to build FlashTool from sources?

**Comment by bungabunga** [comment]
@Androxyde but it always worked to download linux version from flashtool.net, unpack it and run with sudo ./FlashTool

it doesn't anymore.

**Comment by Schweineschwarte** [comment]
@bungabunga 
Can you open a new issue, please? You have an other problem (NullPointerException).

**Comment by bungabunga** [comment]
ok, i did. #37

**Comment by MobilGear** [comment]
hello any updates on this, i have archlinux x64 with cinnanmon desktop, the program works but after pacaman -Syu i have the error
