### ISSUE TITLE
Linux FlashToolConsole errors

### ISSUE THREAD

**Issue by superr** [Androxyde/Flashtool#40]
Hello,

First off, great tool. Thanks :) 

Using the gui I am able to extract kernel.sin and system.sin without issues. However, when using FlashToolConsole I get errors. Running 64-bit 
[z5_kernel.sin.zip](https://github.com/Androxyde/Flashtool/files/418262/z5_kernel.sin.zip)
Ubuntu 16.04 on z5 dual sin files. Here is the command I am using:
```
superr@studio:~/android/FlashTool$ ./FlashToolConsole --action=extract --file=/home/superr/android/z5dual/kernel.sin
```
and here is the output:
```
Used java home : ./x10flasher_lib/linjre64
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/custom/StyledText
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.createBuilder(PluginBuilder.java:149)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:119)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:888)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:828)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:820)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:449)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:197)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:209)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:492)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:246)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:171)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:82)
	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:64)
	at gui.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.custom.StyledText
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
```
Thanks for your help :)

**Comment by denysvitali** [comment]
I've had the exact same error.  
To fix it, you only have to change [this](https://github.com/Androxyde/Flashtool/blob/3cc4a0a8d0a70a71c8839d8b86cb10f4861263f5/ProgramExe/FlashToolConsole#L176) to:
```
SWT=./x10flasher_lib/swtlin/x86_64/org.eclipse.swt.gtk.linux.x86_64_3.105.2.v20161122-0613.jar
```

In my case (I have downloaded the torrented version of the distributed SW), I had to change line 176.

**Comment by elboulangero** [comment]
I have the same issue with version `0.9.24.4`.

**Comment by elboulangero** [comment]
```
Used java home : ./x10flasher_lib/linjre64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/arno/Downloads/xperia/FlashTool/x10flasher_lib/groovy-all-3.0.0-alpha-1.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/custom/StyledText
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
```

**Comment by elboulangero** [comment]
Oh well, not exactly the same. What happens for me is that I get an exception if I run Flashtool as root, however if I run as a normal user (I'm on Linux), it works just fine.

**Comment by hazhheadz** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/custom/StyledText
