### ISSUE TITLE
Hangs on clicking "Create" in Bundle.

### ISSUE THREAD

**Issue by shivdhar** [Androxyde/Flashtool#50]
On Linux (Fedora 25 Workstation Edition):
Flashtool hangs when I click the "Create" button. It works perfectly fine upto then.
Traceback:

java.lang.NullPointerException
	at org.system.DeviceEntry.getFlashScript(DeviceEntry.java:370)
	at gui.BundleCreator$6.widgetSelected(BundleCreator.java:312)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at gui.BundleCreator.open(BundleCreator.java:113)
	at gui.MainSWT$21.widgetSelected(MainSWT.java:504)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at gui.MainSWT.open(MainSWT.java:180)
	at gui.Main.main(Main.java:46)

**Comment by shivdhar** [comment]
Just patched it from 0.9.23.1 to 0.9.23.2. It works fine now. 

Might want to update the torrent to include the patch..

**Comment by zsmav** [comment]
I stumbled upon the same issue in 0.9.23.2

**Comment by DarkSmile92** [comment]
Got same issue in 0.9.23.2.
Solved it by running following command in terminal to termporary allow superuser to access current users XSession:
`xhost si:localuser:root` (until logout)
Then ran flashtool als root:
`sudo ./FlashTool`

Worked without crashing this time.

**Comment by gnihtemoSgnihtemos** [comment]
I still get this error and hang
