### ISSUE TITLE
Bundler: Freeze on "Create"

### ISSUE THREAD

**Issue by solarkraft** [Androxyde/Flashtool#78]
Thanks for fixing the "no loader.sin" issue, but unfortunately this also introduced a new bug (on 64 Bit Linux, creating a bundle for the F53XX/X Compact. 

When clicking "Create" in the Bundler Flashtool freezes with this message: 
```
java.lang.NullPointerException
	at org.system.DeviceEntry.getFlashScript(DeviceEntry.java:370)
	at gui.BundleCreator$6.widgetSelected(BundleCreator.java:312)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at gui.BundleCreator.open(BundleCreator.java:113)
	at gui.MainSWT$21.widgetSelected(MainSWT.java:504)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at gui.MainSWT.open(MainSWT.java:180)
	at gui.Main.main(Main.java:46)
```

**Comment by solarkraft** [comment]
So this was fixed with Version 0.9.23.2, which is distributed as a patch for Version 0.9.23.1. Please Improve the releases, I'd help. Refer to Issue #79.
