### ISSUE TITLE
Unable to start the program. 

### ISSUE THREAD

**Issue by dyx726** [Androxyde/Flashtool#81]
java.lang.NoClassDefFoundError: delight/rhinosandox/RhinoSandboxes
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.github.markusbernhardt.proxy.util.ProxyUtil.buildPacSelectorForUrl(ProxyUtil.java:90)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.createPacSelector(IEProxySearchStrategy.java:114)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:40)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:216)
	at org.system.Proxy.setProxy(Proxy.java:34)
	at gui.MainSWT.createContents(MainSWT.java:1272)
	at gui.MainSWT.open(MainSWT.java:123)
	at gui.Main.main(Main.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
Caused by: java.lang.ClassNotFoundException: delight.rhinosandox.RhinoSandboxes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

version：0.9.24.4
system：win8.1 64bit

**Comment by asiaon123** [comment]
me too

**Comment by jomplin** [comment]
把SS关了就行……

**Comment by malakmrsha** [comment]
ok so here is the workaround.

disable network and flashtool will start.

more info - not sure why but when my vpn is to non restricted country it will load even with network on.

if i connect to restricted country (like GE) it will pop up with this error.

hope the workaround helps.

**Comment by sanqit** [comment]
> ok so here is the workaround.
> 
> disable network and flashtool will start.
> 
> more info - not sure why but when my vpn is to non restricted country it will load even with network on.
> 
> if i connect to restricted country (like GE) it will pop up with this error.
> 
> hope the workaround helps.

yes, it's was very helpful for me!!

**Comment by jiangqingbo** [comment]
> 把SS关了就行……

SS 指的是VPN翻墙的吗？
