### ISSUE TITLE
Not able to flash stock ftf to sony xperia sp

### ISSUE THREAD

**Issue by sujan46** [Androxyde/Flashtool#82]
Hi,

When I try to flash my Xperia SP to stock i am getting the 

> java.lang.NullPointerException.

OS:

> Ubuntu 16.04

Flashtool version

> v09.23,1

Attached the logs below

FlashTool Logs:

> 11/010/2018 02:10:48 - INFO  - Selected Bundle for Sony Xperia SP(C5302). FW release : 12.1.A.1.201. Customization : Generic
> 11/010/2018 02:10:49 - INFO  - Preparing files for flashing
> 11/011/2018 02:11:21 - INFO  - Please connect your device into flashmode.
> 11/011/2018 02:11:36 - INFO  - Device connected in flash mode
> 11/011/2018 02:11:36 - INFO  - Opening device for R/W
> 11/011/2018 02:11:36 - INFO  - Device ready for R/W.
> 11/011/2018 02:11:36 - INFO  - Reading device information
> 11/011/2018 02:11:36 - INFO  - Phone ready for flashmode operations.
> 11/011/2018 02:11:36 - INFO  - Opening TA partition 2
> 11/011/2018 02:11:36 - INFO  - Current device : Unknown: Jan 19 2014/22:13:32 - CB51242WHZ - Unknown: Jan 19 2014/22:13:32 - Unknown: Jan 19 2014/22:13:32 - Unknown: Jan 19 2014/22:13:32
> 11/011/2018 02:11:36 - INFO  - Closing TA partition
> 11/011/2018 02:11:36 - INFO  - Start Flashing
> 11/011/2018 02:11:36 - INFO  - Processing loader.sin
> 11/011/2018 02:11:36 - INFO  -     Checking header
> 11/011/2018 02:11:36 - INFO  -     Flashing data
> 11/011/2018 02:11:38 - INFO  - Loader : S1_Root_7054 - Version : R5G006 / Boot version : R11B023 / Bootloader status : UNROOTABLE
> 11/011/2018 02:11:38 - INFO  - Max packet size set to 64K
> 11/011/2018 02:11:38 - INFO  - USB buffer size set to 512K
> 11/011/2018 02:11:38 - INFO  - Ending flash session
> 11/011/2018 02:11:38 - ERROR - null
> 11/011/2018 02:11:38 - ERROR - Error flashing. Aborted

Java Exception:

> java.lang.NullPointerException
> 	at flashsystem.X10flash.flashDevice(X10flash.java:717)
> 	at gui.tools.FlashJob.run(FlashJob.java:44)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by mscalin-dt** [comment]
Use older version (09.22.3 should work).
