### ISSUE TITLE
Java error when launching Flashtool

### ISSUE THREAD

**Issue by KyleSforza** [Androxyde/Flashtool#84]
The error I am receiving  

`java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 5.2.0
Found:    5.1.0
C:\Flashtool\.\.;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\FileBot\;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Users\ethan\AppData\Local\Microsoft\WindowsApps;c:\flashtool\x10flasher_lib\winjre64\bin.
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:199)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.readIEProxyConfig(IEProxySearchStrategy.java:67)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:38)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:216)
	at org.system.Proxy.setProxy(Proxy.java:34)
	at gui.MainSWT.createContents(MainSWT.java:1272)
	at gui.MainSWT.open(MainSWT.java:123)
	at gui.Main.main(Main.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
`

**Comment by Soitora** [comment]
Exactly the same issue here...

**Comment by projektilski** [comment]
Same issue here. Windows 10 x64bit, Java 1.8.0_162 32bit

**Comment by xd1986k** [comment]
Same error here. Reverting to flashtool-0.9.23.1-windows worked for me.

**Comment by Soitora** [comment]
Error occured while launching the 64bit executable. fixed when launching using 32bit executable.
I'm on Windows 10 Professional 64-bit, latest public release.

**Comment by thoatswold** [comment]
I also had this problem when launching the 0.9.25 64-bit executable on Windows 10 Home 64-bit. I couldn't use the 32-bit executable because for some reason it wasn't installed. However, there is a fairly simple workaround, as suggested by the solutions hinted at in the error message. Create a new system environment variable called JAVA_TOOL_OPTIONS with the value '-Djna.nosys=true' (without the quotes). Flashtool then opens normally.

[Computer > System Properties > Advanced > Environment Variables > System variables > New...]
