### ISSUE TITLE
flashtool can't unpack xz2 .sin

### ISSUE THREAD

**Issue by alviteri** [Androxyde/Flashtool#87]
org.sinfile.parsers.SinFileException: Not a sin file
	at org.sinfile.parsers.SinFile.<init>(SinFile.java:86)
	at gui.SinEditor$5.widgetSelected(SinEditor.java:190)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at gui.SinEditor.open(SinEditor.java:63)
	at gui.MainSWT$17.widgetSelected(MainSWT.java:428)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at gui.MainSWT.open(MainSWT.java:190)
	at gui.Main.main(Main.java:46)

**Comment by alviteri** [comment]
ping @Androxyde

**Comment by MartinX3** [comment]
Tried with 0.9.25.0 to open the system_X-FLASH-ALL-B6B5.sin
Result
ERROR - This sin version is not yet supported

According to the changelog, the XZ2 should be supported now.

@alviteri 
@Androxyde 
@rogers0
