### ISSUE TITLE
java error on start of flashtool

### ISSUE THREAD

**Issue by safwan051432** [Androxyde/Flashtool#9]
cannot open flashtool due to java error, deleted and installed java again, but still problem is there

**Comment by Androxyde** [comment]
Can you post stderr and stdout logs ?

**Comment by safwan051432** [comment]
java.lang.ClassNotFoundException: gui.Main
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
at com.exe4j.runtime.WinLauncher.main(Unknown Source)

**Comment by Tastyboi** [comment]
I am having the exact same issue. I'm using Windows 7 64bit.

**Comment by techie25** [comment]
Hi, I am getting below error while running flashtool 

java.lang.NullPointerException
	at org.logger.MyLogger.initProperties(MyLogger.java:36)
	at org.logger.MyLogger.setLogDest(MyLogger.java:28)
	at gui.Main.main(Main.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)

**Comment by jacksun101** [comment]
I am getting the same error.

**Comment by ydnk68** [comment]
Any solution, somebody?

**Comment by Teyken** [comment]
Ditto,
Working fine and suddenly this error starts appearing every time

**Comment by cheskos** [comment]
Having same issue here

**Comment by ydnk68** [comment]
Try to reinstall 18.5/6 version (uninstall the old one and delete all old folders and etc.).
