### ISSUE TITLE
Can't locate FTF files

### ISSUE THREAD

**Issue by fsierpinski** [Androxyde/Flashtool#92]
I've placed the ftf files on firmwares folder but flashtool doesn't show it to flash. I've made some with flashtool itself and still doesn't show them.
![yfhbyis](https://user-images.githubusercontent.com/38745540/41446306-3814827a-7025-11e8-9129-26ddb18882ba.png)

**Comment by Titokhan** [comment]
Can you please try another folder name which doesn't starts with a '.'?

**Comment by emartynov** [comment]
Same issue on Mac. Doesn't work also with folder without `.` in name.

**Comment by thaarok** [comment]
I had the same issue - caused by failed "devices" downloading:
```
$ ./FlashTool 
Not running as root but Sony/SonyEriccson Vendor ID found on your udev rules
if Flashing didn't work well, run flashtool as root
/home/jkalina/Downloads/Flashtool/x10flasher_native/udev
19/03/2023 22:03:55 - INFO  - <- This level is successfully initialized
19/03/2023 22:03:55 - INFO  - JAVA_HOME : /home/jkalina/Downloads/Flashtool/jre
org.eclipse.jgit.api.errors.TransportException: git@github.com:Androxyde/devices.git: remote hung up unexpectedly
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:325)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:191)
	at org.flashtool.system.DevicesGit.cloneRepository(DevicesGit.java:42)
	at org.flashtool.system.DevicesGit.pullRepository(DevicesGit.java:85)
	at org.flashtool.system.DevicesGit.gitSync(DevicesGit.java:28)
	at org.flashtool.gui.tools.DevicesSyncJob.run(DevicesSyncJob.java:27)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:Androxyde/devices.git: remote hung up unexpectedly
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:313)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:151)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1405)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:233)
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.transport.SshSessionFactory.getSession(org.eclipse.jgit.transport.URIish, org.eclipse.jgit.transport.CredentialsProvider, org.eclipse.jgit.util.FS, int)" because "this.sch" is null
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
	... 12 more
```

When I downloaded https://github.com/Androxyde/devices manually into `~/.flashTool/devices` and restarted FlashTool, it started detecting FTF files - I see the firmware after selecting the folder with the FTF file.
