### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by DevilFu** [Androxyde/Flashtool#96]
An error has occured during startup
java.lang.NoClassDefFoundError: delight/rhinosandox/RhinoSandboxes
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.github.markusbernhardt.proxy.util.ProxyUtil.buildPacSelectorForUrl(ProxyUtil.java:90)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.createPacSelector(IEProxySearchStrategy.java:114)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:40)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:216)
	at org.system.Proxy.setProxy(Proxy.java:34)
	at gui.MainSWT.createContents(MainSWT.java:1272)
	at gui.MainSWT.open(MainSWT.java:123)
	at gui.Main.main(Main.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
Caused by: java.lang.ClassNotFoundException: delight.rhinosandox.RhinoSandboxes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

Recently my flashtool can't start successfully and this's the error information.I've installed the Win10 system over and over again but still doesn't work.Any suggestion?

**Comment by Shaloc** [comment]
Just turn off the shadowsocks or any other proxy tools (or set them to direct link mode) and see if it works for you.

**Comment by zypA13510** [comment]
Probably duplicate of #81
